extends Node

var endings = {
	"ESCAPE": "(green)You found all of the missing parts of your car!(white) \n\n You frantically replace the parts and scramble into the front seat. The engine roars to life and you slam your foot on the gas. Your wheels spin until they finally find purchase, kicking up dirt and dead vegetation.\n\n You peel out of ________, your eyes wild as you stare in horror into the rearview mirror. In the reflection you can see the outline of an indescribable horror. You slam your eyelids shut as you zoom away. \n\n It is weeks later. You still cannot get the image of that creature out of your mind, the image of the carvings and symbols are burned into your corneas. \n\n You sit at a folding table looking out the window you look out every day. The doctor passes and puts their hand on your shoulder asking how you have been feeling today. \n\n You don't answer.",
	"ESCAPE_INSANE": "(green)You found all of the missing parts of your car!(white) \n\n You frantically replace the parts and scramble into the front seat. The engine roars to life and you slam your foot on the gas. Your wheels spin until they finally find purchase, kicking up dirt and dead vegetation.\n\n ",
	"ESCAPE_SANE": "(green)You found all of the missing parts of your car!(white) \n\n You frantically replace the parts and scramble into the front seat. The engine roars to life and you slam your foot on the gas. Your wheels spin until they finally find purchase, kicking up dirt and dead vegetation.\n\n ",
	"KILL": "(green)You killed the creature.(white) \n\n The sixth bullet tears through the monster with a horrible ripping sound, a sound that will haunt you long after you leave this horrible place.\n\n Your car is still broken so you stumble down the main road into the darkness, thumb to the sky and a prayer to a god you no longer believe in on your lips.",
	"MONSTER": "(green)The creature gets you.(white)",
	"RIVER": "(green)You throw yourself into the crashing white water.(white) \n\n For just a moment, the freedom of the fall felt worth it, the knowledge you no longer need to be afraid was a rush. \n\n For just a moment...",
	"INSANITY": "(green)The madness consumes you.(white) \n\n It was too much...you couldn't take it and something inside your mind broke beneath the pressure of the horror.",
	"RITUAL": "(green)You joined the Esoteric Order Of Dagon.(white) \n\n You forget your world and your life from before. You yearn for the time with no end. No today. No yesterday. No tomorrow. A beautiful place where you will spend infinity with the Great One."
}
